"""Generate and verify native adapters from the hash-bound Python IDA evidence.

PE reads only check hashes, RVA bounds and already documented entry bytes;
instruction analysis remains in ida_minimap_versions.py (idapro).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
from pathlib import Path

BASE = 0x140000000
ENTRIES = {
    "submit": bytes.fromhex("4c8bdc4883ec78"),
    "flush": bytes.fromhex("41564883ec30"),
    "enqueue": bytes.fromhex("41564883ec30"),
    "cancel": bytes.fromhex("4883ec28488b15"),
}


def profiles(evidence):
    result, known = [], {}
    for version in evidence["versions"]:
        digest = version["sha256"]
        if digest in known:
            known[digest]["label"] += "/" + version["label"]
            continue
        assert version["static_relocatable"]
        item = {"label": version["label"], "sha256": digest, "path": version["path"]}
        for key in ENTRIES:
            function = version["file_functions"][key]
            assert function["same_masked_body"]
            item[key] = int(function["rva"], 0)
        for key, source in (("manager", "manager"), ("allocator", "allocator"), ("retirePoolOwner", "retire_pool_owner")):
            item[key] = int(version["file_globals"][source]["rva"], 0)
        for key, source in (("menu", "menu"), ("gameData", "game_data"), ("eventFlags", "event_flags"), ("field", "field")):
            item[key] = int(version["hooks"][source]["rva"], 0)
        for key in ("repository", "reveal"):
            item[key] = int(version["map_globals"][key], 0) - BASE
        layout = version["layout"]
        item["layout"] = [layout[k] for k in ("menu_owner", "owner_view", "menu_info", "screen_state", "grace_stride", "grace_normal")]
        item["layout"] += [int(layout["alternate_icons"]), 7 if 61 in layout["native_area_codes"] else 3, version["repository"]["count"]]
        known[digest] = item
        result.append(item)
    reference = evidence["reference"]
    # RVAs confirmed on the Steam 1.17.1 baseline, distinct from 1.17.
    result.append({
        "label": reference["version"], "sha256": reference["sha256"],
        "path": r"D:\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe",
        "submit": 0x26EEB60, "flush": 0x26EED40, "enqueue": 0x26F42E0, "cancel": 0x26EE2C0,
        "manager": 0x48611A0, "allocator": 0x3D8B360, "retirePoolOwner": 0x4860D70,
        "menu": 0x3D6F820, "gameData": 0x3D61F98, "eventFlags": 0x3D6C4B8, "field": 0x3D6D248,
        "repository": 0x3D85F58, "reveal": 0x3D71030,
        "layout": [0x80, 0x250, 0x720, 0x730, 0x350, 0x348, 1, 7, 194],
    })
    assert len(result) == evidence["coverage"]["unique_executables"] + 1
    return result


def render(items):
    lines = ["// Generated by tools/generate_minimap_profiles.py; do not edit RVAs by hand."]
    keys = ("submit", "flush", "enqueue", "cancel", "manager", "allocator", "retirePoolOwner",
            "menu", "gameData", "eventFlags", "field", "repository", "reveal")
    for item in items:
        digest = bytes.fromhex(item["sha256"])
        lines.extend(["{", f'    "{item["label"]}",', "    {"])
        for start in (0, 16):
            lines.append("        " + ", ".join(f"0x{byte:02x}" for byte in digest[start:start + 16]) + ",")
        lines.append("    },")
        for start, end in ((0, 4), (4, 7), (7, 13)):
            lines.append("    " + ", ".join(hex(item[k]) for k in keys[start:end]) + ",")
        lines.extend(["    {sizeof(ERGameLayout), " + ", ".join(hex(v) for v in item["layout"]) + "},", "},"])
    return chr(10).join(lines) + chr(10)


def verify_file(item, path):
    with path.open("rb") as stream:
        assert hashlib.file_digest(stream, "sha256").hexdigest() == item["sha256"], path
        stream.seek(0x3C)
        pe = struct.unpack("<I", stream.read(4))[0]
        stream.seek(pe)
        assert stream.read(4) == b"PE\0\0"
        machine, count, _, _, _, optional_size, _ = struct.unpack("<HHIIIHH", stream.read(20))
        assert machine == 0x8664
        optional = stream.read(optional_size)
        assert struct.unpack_from("<H", optional)[0] == 0x20B
        assert struct.unpack_from("<Q", optional, 24)[0] == BASE
        image_size = struct.unpack_from("<I", optional, 56)[0]
        sections = []
        for _ in range(count):
            section = stream.read(40)
            virtual_size, rva, raw_size, raw_offset = struct.unpack_from("<IIII", section, 8)
            sections.append((rva, virtual_size, raw_size, raw_offset, struct.unpack_from("<I", section, 36)[0]))
        for key, entry in ENTRIES.items():
            rva = item[key]
            candidates = [s for s in sections if s[0] <= rva and rva + len(entry) <= s[0] + s[2]]
            assert len(candidates) == 1 and candidates[0][4] & 0x20000000, (path, key)
            section = candidates[0]
            stream.seek(section[3] + rva - section[0])
            assert stream.read(len(entry)) == entry, (path, key, hex(rva))
        for key in ("manager", "allocator", "retirePoolOwner", "menu", "gameData", "eventFlags", "field", "repository", "reveal"):
            size = 1 if key == "reveal" else 8
            assert item[key] + size <= image_size
            assert any(s[0] <= item[key] and item[key] + size <= s[0] + max(s[1], s[2]) and s[4] & 0x40000000 for s in sections), (path, key)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence", type=Path, default=Path("docs/minimap-version-compatibility.evidence.json"))
    parser.add_argument("--output", type=Path, default=Path("src/util/gameprofiles.inc"))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--verify-exes", action="store_true")
    args = parser.parse_args()
    evidence = json.loads(args.evidence.read_text(encoding="utf-8"))
    items = profiles(evidence)
    content = render(items)
    if args.check:
        assert args.output.read_text(encoding="utf-8") == content, "Regenerate gameprofiles.inc"
    else:
        args.output.write_text(content, encoding="utf-8")
    if args.verify_exes:
        by_hash = {p["sha256"]: p for p in items}
        for version in evidence["versions"]:
            verify_file(by_hash[version["sha256"]], Path(version["path"]))
        verify_file(items[-1], Path(items[-1]["path"]))
    print(json.dumps({"profiles": len(items), "historical_directories": evidence["coverage"]["directories"],
                      "exes_verified": args.verify_exes, "generated_table_matches": True}))


if __name__ == "__main__":
    main()
